#basic auth password
password: pwd

server:
  applicationConnectors:
     - type: http
       port: 8088
     - type: https
       port: 8443
       keyStorePath: keystore.jks
       keyStorePassword: changeit
       validateCerts: false
       

database: 
       driverClass: com.mysql.jdbc.Driver
       user: rgabay
       password: rgabay
       url: jdbc:mysql://localhost:3306/kaban

logging:
       level: INFO

#elasticsearch endpoint configs  
url: http://localhost:9200
type: people
index: hr